name: Nicholas Reich
title: "Reich Lab: Biostatistics and Infectious Disease Epidemiology"

url: "shv38339.github.io/reichlab/"
baseurl: "/reichlab"

paginate: 5
paginate_path: "/reichlab/page:num"
excerpt_separator: <!--more-->

markdown: kramdown

